In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[10,20,np.NaN,30],[40,np.NaN,np.NaN,50],[10,40,40,50]],
               columns="a b c d".split())
print(df.isna().sum(axis=1))
print(df.dropna())
print(df.dropna(axis=1))
print(df.dropna(thresh=3))
print(df.dropna(thresh=3, axis=1))
print(df.dropna(subset=['b']))
print(df.dropna(how='all'))

0    1
1    2
2    0
dtype: int64
    a     b     c   d
2  10  40.0  40.0  50
    a   d
0  10  30
1  40  50
2  10  50
    a     b     c   d
0  10  20.0   NaN  30
2  10  40.0  40.0  50
    a   d
0  10  30
1  40  50
2  10  50
    a     b     c   d
0  10  20.0   NaN  30
2  10  40.0  40.0  50
    a     b     c   d
0  10  20.0   NaN  30
1  40   NaN   NaN  50
2  10  40.0  40.0  50


In [2]:
from sklearn.impute import SimpleImputer

In [3]:
si=SimpleImputer(strategy='mean')
df_mean=si.fit_transform(df)
print(df_mean)

[[10. 20. 40. 30.]
 [40. 30. 40. 50.]
 [10. 40. 40. 50.]]


In [4]:
si=SimpleImputer(strategy='median')
df_median=si.fit_transform(df)
print(df_median)

[[10. 20. 40. 30.]
 [40. 30. 40. 50.]
 [10. 40. 40. 50.]]


In [5]:
si=SimpleImputer(strategy='most_frequent')
df_most=si.fit_transform(df)
print(df_most)

[[10. 20. 40. 30.]
 [40. 20. 40. 50.]
 [10. 40. 40. 50.]]


In [7]:
df1=pd.read_csv('C:/Users/HP/Downloads/adult.data',
                na_values=' ?',header=None)
#print(df1.isna().sum())
s=SimpleImputer(strategy="most_frequent")
df=s.fit_transform(df1)
df=pd.DataFrame(df)
#print(df.isna().sum())
print(df.head())

   0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10 11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174  0  40   
1     Exec-managerial         Husband   White     Male     0  0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0  0  40   
3   Handlers-cleaners         Husband   Black     Male     0  0  40   
4      Prof-specialty            Wife   Black   Female     0  0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=

In [8]:
c=[1,3,5,6,7,8,9,13,14]
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in c:
    df[i]=le.fit_transform(df[i])
print(df.head())

   0   1       2   3   4   5   6   7   8   9     10 11  12  13  14
0  39   6   77516   9  13   4   0   1   4   1  2174  0  40  38   0
1  50   5   83311   9  13   2   3   0   4   1     0  0  13  38   0
2  38   3  215646  11   9   0   5   1   4   1     0  0  40  38   0
3  53   3  234721   1   7   2   5   0   2   1     0  0  40  38   0
4  28   3  338409   9  13   2   9   5   2   0     0  0  40   4   0


In [12]:
df=pd.DataFrame([[1,23,'male','good'],[2,89,'female','great'],[3,44,'male','great'],[3,67,'female','good']],)
print(df)

   0   1       2      3
0  1  23    male   good
1  2  89  female  great
2  3  44    male  great
3  3  67  female   good


In [11]:
import numpy as np
import pandas as pd
df=pd.read_csv("adult.data", header=None, na_values=" ?")
#df.head()
#df[1].unique()
print(df.isna().sum())

In [8]:
from sklearn.impute import SimpleImputer
df=pd.DataFrame(
    SimpleImputer(strategy="most_frequent").fit_transform(df))

In [13]:
from sklearn.preprocessing import LabelEncoder
columns=[1,3,5,6,7,8,9,13,14]
for i in columns:
    df[i]=LabelEncoder().fit_transform(df[i])
#print(df.head())


In [18]:
df=pd.DataFrame([[1,'x','male','good'],[2,'y','female','good'],
                [3,'a','male','average']], 
                columns=['id','name','gender','feedback'])

In [19]:
gen={'male':1,'female':2}
#df['gender']=df['gender'].map(gen)
df=pd.get_dummies(df,columns=['feedback','gender'])
print(df)

   id name  feedback_average  feedback_good  gender_female  gender_male
0   1    x                 0              1              0            1
1   2    y                 0              1              1            0
2   3    a                 1              0              0            1


In [29]:
df2=pd.DataFrame([[1.0],[2.0],[3.0],[4.0],[5.0],[6.0]])
#print(df2)

In [30]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [32]:
df_norm=pd.DataFrame(MinMaxScaler().fit_transform(df2))
df_stan=pd.DataFrame(StandardScaler().fit_transform(df2))
print(df_norm,df_stan)

     0
0  0.0
1  0.2
2  0.4
3  0.6
4  0.8
5  1.0          0
0 -1.46385
1 -0.87831
2 -0.29277
3  0.29277
4  0.87831
5  1.46385
